/*
 * File: app/controller/MyController.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('IdiomesApp.controller.MyController', {
    extend: 'Ext.app.Controller',

    config: {
        control: {
            "#paraulesList": {
                itemtap: 'onListpanelTap'
            }
        }
    },

    onListpanelTap: function(dataview, index, target, record, e, options) {
        IdiomesApp.titol=record.get('textcat');
        //Auxiliar que ens servirà quan tornem de crear una nova instrucció
        IdiomesApp.titolAux=record.get('textcat');

        Ext.getCmp('myToolBar').setTitle(IdiomesApp.titol);
    }

});