/*
 * File: app/model/paraulaModel.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('IdiomesApp.model.paraulaModel', {
    extend: 'Ext.data.Model',

    config: {
        fields: [
            {
                name: 'id',
                allowNull: false,
                type: 'auto'
            },
            {
                name: 'textcat',
                allowNull: false,
                type: 'string'
            },
            {
                name: 'textjap',
                allowNull: false,
                type: 'string'
            },
            {
                name: 'pronjap',
                allowNull: false,
                type: 'string'
            },
            {
                name: 'idLlista',
                allowNull: false,
                type: 'int'
            }
        ],
        validations: [
            {
                type: 'presence',
                field: 'id'
            },
            {
                type: 'presence',
                field: 'textcat'
            },
            {
                type: 'presence',
                field: 'textjap'
            },
            {
                type: 'presence',
                field: 'pronjap'
            }
        ]
    }
});