/*
 * File: app/view/addParaula.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('IdiomesApp.view.addParaula', {
    extend: 'Ext.form.Panel',
    alias: 'widget.addparaula',

    config: {
        id: 'addParaula',
        itemId: 'addParaula',
        layout: {
            pack: 'center',
            type: 'vbox'
        },
        scrollable: 'vertical',
        items: [
            {
                xtype: 'fieldset',
                id: 'formParaula',
                itemId: 'fieldsetparaula',
                title: 'Afegir una paraula',
                items: [
                    {
                        xtype: 'textfield',
                        label: 'Català',
                        name: 'textcat',
                        required: true
                    },
                    {
                        xtype: 'textfield',
                        label: 'Kanji',
                        name: 'textjap',
                        required: true
                    },
                    {
                        xtype: 'textfield',
                        label: 'Pronunciació (Jap)',
                        name: 'pronjap',
                        required: true
                    }
                ]
            }
        ]
    }

});