/*
 * File: app/view/DetallParaula.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('IdiomesApp.view.DetallParaula', {
    extend: 'Ext.Container',

    config: {
        id: 'DetallParaula',
        itemId: 'DetallParaula',
        style: 'background-color: #ccc;',
        ui: 'light',
        width: '100%',
        layout: {
            type: 'fit'
        },
        scrollable: false,
        items: [
            {
                xtype: 'container',
                cls: [
                    'card1'
                ],
                docked: 'top',
                id: 'paraulaTarjeta',
                minHeight: 500,
                tpl: [
                    '<div>',
                    '    <h1>{textcat}</h1>',
                    '    <h2>{textjap}</h2>',
                    '    <p>{pronjap}</p>',
                    '</div>'
                ],
                ui: 'light',
                width: '100%',
                layout: {
                    type: 'fit'
                },
                scrollable: 'vertical'
            }
        ]
    }

});