/*
 * File: app/view/Game.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('IdiomesApp.view.Game', {
    extend: 'Ext.Container',

    config: {
        id: 'game',
        style: 'background-color: #ccc;',
        items: [
            {
                xtype: 'carousel',
                height: 300,
                id: 'carruselParaules',
                itemId: 'carruselParaules',
                items: [
                    {
                        xtype: 'container',
                        border: 1,
                        cls: [
                            'card2'
                        ],
                        height: 300,
                        html: '',
                        id: 'pregunta',
                        tpl: [
                            '<div style="height:300px;">',
                            '    <p>{nom}</p>',
                            '</div>'
                        ],
                        layout: {
                            animation: 'flip',
                            type: 'card'
                        }
                    },
                    {
                        xtype: 'container',
                        border: 1,
                        cls: [
                            'card3'
                        ],
                        height: 300,
                        id: 'resposta',
                        tpl: [
                            '<div style="height:300px;">',
                            '    <p>{id}</p>',
                            '</div>'
                        ],
                        ui: '',
                        layout: {
                            animation: 'flip',
                            type: 'card'
                        }
                    }
                ]
            },
            {
                xtype: 'button',
                docked: 'left',
                height: 50,
                hidden: true,
                id: 'fallada',
                left: 15,
                top: 315,
                ui: 'decline-round',
                width: 140,
                iconCls: 'delete',
                iconMask: true,
                text: 'Fallada'
            },
            {
                xtype: 'button',
                docked: 'right',
                height: 50,
                hidden: true,
                id: 'encert',
                right: 15,
                top: 315,
                ui: 'confirm-round',
                width: 140,
                iconAlign: 'right',
                iconCls: 'favorites',
                iconMask: true,
                text: 'Encert'
            }
        ],
        listeners: [
            {
                fn: 'onCarruselParaulesActiveItemChange',
                event: 'activeitemchange',
                delegate: '#carruselParaules'
            }
        ]
    },

    onCarruselParaulesActiveItemChange: function(container, value, oldValue, options) {
        if(value.config.id == 'pregunta'){
            Ext.getCmp('fallada').setHidden(true);
            Ext.getCmp('encert').setHidden(true);
        }else{
            Ext.getCmp('fallada').setHidden(false);
            Ext.getCmp('encert').setHidden(false);
        }
    }

});