/*
 * File: app/view/ListPanel3.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('IdiomesApp.view.ListPanel3', {
    extend: 'Ext.Panel',
    alias: 'widget.listpanel3',

    config: {
        id: 'listPanel3',
        layout: {
            type: 'fit'
        },
        items: [
            {
                xtype: 'list',
                id: 'llistesestudiListFlashcards',
                itemId: 'mylist3',
                itemTpl: [
                    '<div>',
                    '    <h3>{nom}</h3>',
                    '</div>'
                ],
                loadingText: 'Carregant...',
                store: 'llistaJson',
                disableSelection: false,
                grouped: true,
                onItemDisclosure: false,
                indexBar: true
            }
        ],
        listeners: [
            {
                fn: 'onLlistesestudiListFlashcardsItemTap',
                event: 'itemtap',
                delegate: '#llistesestudiListFlashcards'
            }
        ]
    },

    onLlistesestudiListFlashcardsItemTap: function(dataview, index, target, record, e, options) {
        Ext.getCmp('listPanel3').setHidden(true);
        IdiomesApp.titol="Aprenent: " + record.get('nom');
        Ext.getCmp('myToolBar').setTitle(IdiomesApp.titol);
        Ext.getCmp('nouJoc').setHidden(false);

        var carrusel = Ext.getCmp('carruselParaules');

        if (carrusel) {
            Ext.getCmp('game').destroy();
        }

        //console.log(record.get('id'));
        Ext.getCmp('flashcards').setActiveItem({
            xclass: 'IdiomesApp.view.Game'
        });

        Ext.getCmp('pregunta').setRecord(record);
        Ext.getCmp('resposta').setRecord(record);
    }

});