/*
 * File: app/view/ListPanel.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('IdiomesApp.view.ListPanel', {
    extend: 'Ext.Panel',
    alias: 'widget.listpanel',

    config: {
        id: 'listPanel',
        layout: {
            type: 'fit'
        },
        items: [
            {
                xtype: 'list',
                id: 'paraulesList',
                itemId: 'mylist',
                itemTpl: [
                    '<div style="height:85px;">',
                    '    <p>{textcat}</p>',
                    '    <p>{textjap}</p>',
                    '    <p>{pronjap}</p>',
                    '</div>'
                ],
                loadingText: 'Carregant...',
                store: 'paraulaJson'
            }
        ],
        listeners: [
            {
                fn: 'onParaulesListItemTap',
                event: 'itemtap',
                delegate: '#paraulesList'
            }
        ]
    },

    onParaulesListItemTap: function(dataview, index, target, record, e, options) {
        Ext.getCmp('listPanel').setHidden(true);
        Ext.getCmp('enrere').setHidden(false);
        Ext.getCmp('novaParaula').setHidden(true);
        Ext.getCmp('editarParaula').setHidden(false);
        IdiomesApp.titol="Paraula: "+record.get('id');
        Ext.getCmp('myToolBar').setTitle(IdiomesApp.titol);

        console.log('onParaulesListItemTap');

        var tarjeta = Ext.getCmp('DetallParaula');

        if (tarjeta) {
            Ext.getCmp('diccionari').setActiveItem(tarjeta);
        } else {
            /*console.log(record.get('id'));
            console.log(record);*/
            Ext.getCmp('diccionari').setActiveItem({
                xclass: 'IdiomesApp.view.DetallParaula'
            });

        }

        Ext.getCmp('paraulaTarjeta').setRecord(record);
        IdiomesApp.paraula=record.get("id");
    }

});