/*
 * File: app/store/llistaJson.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('IdiomesApp.store.llistaJson', {
    extend: 'Ext.data.Store',

    requires: [
        'IdiomesApp.model.llistaModel'
    ],

    config: {
        autoLoad: true,
        model: 'IdiomesApp.model.llistaModel',
        storeId: 'llistaJson',
        proxy: {
            type: 'ajax',
            url: 'data/llista.json',
            reader: {
                type: 'json',
                rootProperty: 'data'
            }
        },
        sorters: {
            id: 'ordenaLlista',
            property: 'nom'
        },
        listeners: [
            {
                fn: 'onJsonstoreAddrecords',
                event: 'addrecords'
            },
            {
                fn: 'onJsonstoreRemoverecords',
                event: 'removerecords'
            },
            {
                fn: 'onJsonstoreLoad',
                event: 'load'
            }
        ]
    },

    onJsonstoreAddrecords: function(store, records, eOpts) {
        Ext.getCmp('menuPanel').getTabBar().getComponent(1);

        var comptadorLlistes = Ext.getCmp('menuPanel').getTabBar().getComponent(1)._badgeText; 

        Ext.getCmp('menuPanel').getTabBar().getComponent(1).setBadgeText(comptadorLlistes+1);
    },

    onJsonstoreRemoverecords: function(store, records, indices, eOpts) {
        Ext.getCmp('menuPanel').getTabBar().getComponent(1);

        var comptadorLlistes = Ext.getCmp('menuPanel').getTabBar().getComponent(1)._badgeText; 

        Ext.getCmp('menuPanel').getTabBar().getComponent(1).setBadgeText(comptadorLlistes-1);
    },

    onJsonstoreLoad: function(store, records, successful, operation, eOpts) {
        Ext.getCmp('menuPanel').getTabBar().getComponent(1);

        var comptadorLlistes = this.getCount();

        Ext.getCmp('menuPanel').getTabBar().getComponent(1).setBadgeText(comptadorLlistes);
    }

});